### ISSUE TITLE
gp_MCMC line 38 GlobalPatterns.R question

### ISSUE THREAD

**Issue by anmwinter** [boyuren158/DirichletFactor#1]
Around line 38 
`main.mcmc.shrink( data, start, hyper, sigma.value, sigma.prior, 
                  paste( "C:/Users/Renboyu/Desktop/gp_MCMC/", "res", sep = "/"), 
                  save.obj = c("sigma","Q", "Y","er"), step = 50000, thin=10 )`

What is this supposed to be pointing at? I am guessing it's a library or some software need to run the MCMC portion?

Thanks!
ara

**Comment by boyuren158** [comment]
Dear Ara,

The way this MCMC works is to save the result of each sampling step to a RDS object. This path here "C:/Users/Renboyu/Desktop/gp_MCMC/" is the folder where those RDS objects will be stored. You can specify this as anything you like but do make sure the folder exist.

Best,
Boyu

**Comment by anmwinter** [comment]
Perfect! Thank you.
