### ISSUE TITLE
GlobalPatterns line all.corr call

### ISSUE THREAD

**Issue by anmwinter** [boyuren158/DirichletFactor#2]
Hello,

  On line 38 of the GlobalPatterns example I came across all.corr . I get the following error when I run this:

`Error in sample(1:length(all.corr), 1000, replace = F) : 
  object 'all.corr' not found`

I looked above line 38 and I could find where all.corr was being defined. 

Thanks again!
ara

**Comment by boyuren158** [comment]
Hi Ara,

Sorry for the late reply. Thank you for spotting on this bug. I committed a change to this part of the code and it should be working properly now.

Best,
Boyu

**Comment by anmwinter** [comment]
Thanks! I will dive back into the script. 

ara
